### ISSUE TITLE
Support for hexfloat datatype

### ISSUE THREAD

**Issue by chris-allnutt** [EOSIO/eosjs-fcbuffer#3]
We need to support the hexfloat base data for serialization and deserialization.

http://en.cppreference.com/w/cpp/io/manip/fixed (hexfloat)
http://en.cppreference.com/w/cpp/types/numeric_limits (need to support range of double)

We will be supported by the eos dev team with example cases for testing.  I'll add links to that code/script when it's available.

**Comment by chris-allnutt** [comment]
@jcalfee I saw that EOSIO/eosjs#41 was closed, does that make this one no longer relevant?

**Comment by jcalfee** [comment]
I added "hexfloat base data for serialization and deserialization".  I'm not sure about the "range of double" part, but they only new type is float64 ..
